RADIUS_OF_EARTH = 6371  # In Kms
INTERCOM_DUBLIN_LATITUDE = 53.339428
INTERCOM_DUBLIN_LONGITUDE = -6.257664
MINIMUM_ALLOWED_DISTANCE_FOR_INVITATION = 100  # In Kms

# I/O File names
INPUT_FILE = "customers.txt"
OUTPUT_FILE = "output.txt"
